<?php
const CHATWORK_API_TOKEN = 'YOUR_CHATWORK_API_TOKEN';
const CHATWORK_WEBHOOK_TOKEN = 'YOUR_CHATWORK_WEBHOOK_TOKEN';
const LOG_DIR = '/log/';
const BACKLOG_SPACE_URL = 'https://YOURSPACE.backlog.com';
const BACKLOG_API_KEY = 'YOUR_BACKLOG_API_KEY';
